-- Scheduling for vocabulary, alongside the existing handwriting schedule.
--
-- This is a change of position, recorded deliberately. Vocabulary review used to
-- be Anki's job only, on the reasoning that NaraNote shouldn't compete with a
-- better scheduler. That held while the app had nothing Anki lacked. It now has
-- mining, handwriting checking and the kanji↔word links — so requiring Anki is a
-- limitation rather than a focus, and someone who doesn't use Anki can't use the
-- app at all.
--
-- Export stays one-way and optional: review here, or export and review there.
-- The two are deliberately not synced — reconciling two schedulers is where the
-- real complexity lives, and Anki offers no API for it.

create table vocab_review (
    vocab_id    bigint      primary key references vocab_item (id) on delete cascade,
    user_id     bigint      not null references app_user (id) on delete cascade,
    state       text        not null,  -- LEARNING | REVIEW | RELEARNING
    step        integer,
    stability   double precision,
    difficulty  double precision,
    due         timestamptz not null,
    last_review timestamptz
);

create index idx_vocab_review_due on vocab_review (user_id, due);

create table vocab_attempt (
    id           bigint      generated by default as identity primary key,
    user_id      bigint      not null references app_user (id) on delete cascade,
    vocab_id     bigint      not null references vocab_item (id) on delete cascade,
    attempted_at timestamptz not null default now(),
    rating       text        not null  -- AGAIN | HARD | GOOD | EASY
);

create index idx_vocab_attempt_user_time on vocab_attempt (user_id, attempted_at desc);
