-- Sentences filed under a character, rather than under a word.
--
-- The kanji page could already derive sentences by matching the text of a saved
-- word's sentence, but that only works if a word was saved first — and mining is
-- kanji-first: you pick the character you actually care about in a passage and
-- file the sentence under it, without having to adopt a word you didn't want.
--
-- Kept separate from vocab_item rather than bolted onto it: a word has one
-- sentence, but a sentence belongs to as many characters as you choose to file
-- it under, and those are different shapes.

create table kanji_sentence (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references app_user (id) on delete cascade,
    literal    text        not null references kanji (literal) on delete cascade,
    sentence   text        not null,
    -- Where the passage came from, copied at filing time. Denormalised on
    -- purpose: the source is a fact about that reading session, and editing it
    -- later shouldn't rewrite sentences you already filed.
    source     text,
    created_at timestamptz not null default now(),
    -- Filing the same sentence under the same character twice is a no-op rather
    -- than a duplicate row.
    unique (user_id, literal, sentence)
);

create index idx_kanji_sentence_user_literal
    on kanji_sentence (user_id, literal, created_at desc);
