-- Real accounts, layered onto the existing app_user row rather than a new
-- table: id=1 is already the FK anchor for every per-user table, and its own
-- seeding comment (V4) already planned for real signups to reuse it.
--
-- email/password_hash stay nullable: row 1 doesn't have them yet, and this
-- migration must not block on data that only exists once the one-off claim
-- step (ClaimLocalAccountRunner, --claim-local-account) runs.

alter table app_user
    add column email text,
    add column password_hash text;

create unique index app_user_email_key on app_user (lower(email)) where email is not null;

-- Opaque session tokens. Only the hash is stored — a DB leak alone shouldn't
-- yield a usable session.
create table app_session (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references app_user (id) on delete cascade,
    token_hash text        not null unique,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create index idx_app_session_token on app_session (token_hash);
