-- Temporary table proving the Flyway -> JPA -> Postgres chain is wired.
-- Drop this once the first real feature has its own migration.
create table ping (
    id         bigint generated by default as identity primary key,
    message    text not null,
    created_at timestamptz not null default now()
);

insert into ping (message) values ('naranote is wired end to end');
