-- Email verification: new accounts start unverified and are gated out of the
-- app (see SessionInterceptor) until they click the link mailed to them.
--
-- Existing rows default to true so nobody who registered before this
-- migration — including the claimed local account (V15 / ClaimLocalAccountRunner)
-- — is retroactively locked out. Only rows inserted after this migration ran
-- pick up the new default of false.
alter table app_user add column email_verified boolean not null default true;
alter table app_user alter column email_verified set default false;

-- Opaque, single-use tokens mailed to the user. Same shape as app_session
-- (V15): only the hash is stored, so a DB leak alone can't hand out a
-- working verification link.
create table email_verification_token (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references app_user (id) on delete cascade,
    token_hash text        not null unique,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create index idx_email_verification_token_hash on email_verification_token (token_hash);
