-- Forgot/reset password. Same shape as email_verification_token (V21) and
-- app_session (V15): only the hash is stored, and a shorter TTL than either
-- (see PasswordResetService) because a reset link is more sensitive than a
-- signup confirmation.
create table password_reset_token (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references app_user (id) on delete cascade,
    token_hash text        not null unique,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create index idx_password_reset_token_hash on password_reset_token (token_hash);
