-- A user's personal kanji library: the characters they've chosen to study.
--
-- The kanji table itself stays global reference data — every user sees all
-- 10,384 characters. This is the per-user subset they practise.

create table app_user (
    id           bigint generated by default as identity primary key,
    display_name text not null,
    created_at   timestamptz not null default now()
);

-- One local user until auth lands. Seeded with an explicit id so application
-- code has something stable to reference; the sequence is advanced past it so
-- real signups later don't collide.
insert into app_user (id, display_name) values (1, 'local');
select setval(pg_get_serial_sequence('app_user', 'id'), 1);

create table kanji_library (
    user_id  bigint      not null references app_user (id) on delete cascade,
    literal  text        not null references kanji (literal) on delete cascade,
    added_at timestamptz not null default now(),
    -- How it got here: added by hand, or picked up from sentence mining later.
    source   text        not null default 'MANUAL',
    primary key (user_id, literal)
);

create index idx_kanji_library_user_added on kanji_library (user_id, added_at desc);
