-- Scheduling state for handwriting practice.
--
-- Scoped deliberately to kanji writing: Anki cannot check handwriting, so those
-- reviews have nowhere else to live. Vocabulary reviews stay in Anki, which does
-- them better and already holds the user's history.
--
-- Columns mirror io.github.openspacedrepetition.Card. There is no row until a
-- character has been reviewed once; the due queue treats a missing row as "new,
-- due now", which keeps adding to the library a single write.

create table kanji_review (
    user_id     bigint      not null,
    literal     text        not null,
    state       text        not null,  -- LEARNING | REVIEW | RELEARNING
    step        integer,
    stability   double precision,
    difficulty  double precision,
    due         timestamptz not null,
    last_review timestamptz,
    primary key (user_id, literal),
    foreign key (user_id, literal)
        references kanji_library (user_id, literal) on delete cascade
);

create index idx_kanji_review_due on kanji_review (user_id, due);

-- Every attempt, kept for the per-character history. Ratings and counts only —
-- the drawings themselves are not stored.
create table kanji_attempt (
    id               bigint      generated by default as identity primary key,
    user_id          bigint      not null references app_user (id) on delete cascade,
    literal          text        not null references kanji (literal) on delete cascade,
    attempted_at     timestamptz not null default now(),
    rating           text        not null,  -- AGAIN | HARD | GOOD | EASY
    strokes_drawn    integer,
    strokes_expected integer
);

create index idx_kanji_attempt_user_time on kanji_attempt (user_id, attempted_at desc);
create index idx_kanji_attempt_literal on kanji_attempt (user_id, literal, attempted_at desc);
