-- Study tasks.
--
-- Deliberately not a general to-do list — those are better elsewhere, and a
-- second inbox is a liability. A task here can carry a date (so it lands on the
-- calendar) and a set of kanji (so it can start a practice session). Tasks that
-- reference neither are still allowed, they just do less.
--
-- The other half of the panel is computed, not stored: "4 due", "12 never
-- practised". Those are derived from the library and review tables, so they
-- resolve themselves and can never go stale.

create table task (
    id           bigint      generated by default as identity primary key,
    user_id      bigint      not null references app_user (id) on delete cascade,
    title        text        not null,
    -- A date, not a timestamp: study tasks belong to a day, not a moment.
    due_date     date,
    kanji        text[]      not null default '{}',
    done         boolean     not null default false,
    created_at   timestamptz not null default now(),
    completed_at timestamptz
);

create index idx_task_user_due on task (user_id, due_date);
create index idx_task_user_done on task (user_id, done, created_at desc);
-- Containment index, for "which tasks mention this character".
create index idx_task_kanji on task using gin (kanji);
