-- JMdict, the Japanese-English dictionary, from jmdict-simplified (EDRDG, CC BY-SA).
-- ~218,000 entries.
--
-- The full English edition rather than the "common only" build: mining means
-- pasting real text, and a dictionary that silently lacks uncommon words fails
-- exactly when it's needed. The clutter that common-only avoids is handled by
-- ranking instead — every entry carries a `common` flag, and lookups sort on it.

create table dict_entry (
    id     text    primary key,  -- JMdict ent_seq
    common boolean not null default false
);

-- Kanji writings and kana readings share a table: both are things a tokenizer's
-- output can match against, and the lookup shouldn't care which it hit.
create table dict_form (
    entry_id text    not null references dict_entry (id) on delete cascade,
    text     text    not null,
    is_kana  boolean not null,
    common   boolean not null default false,
    primary key (entry_id, text, is_kana)
);

-- The hot path: given a base form from the tokenizer, find its entries.
create index idx_dict_form_text on dict_form (text);

create table dict_sense (
    id             bigint generated by default as identity primary key,
    entry_id       text   not null references dict_entry (id) on delete cascade,
    ord            int    not null,
    part_of_speech text[] not null default '{}',
    glosses        text[] not null default '{}',
    misc           text[] not null default '{}'
);

create index idx_dict_sense_entry on dict_sense (entry_id, ord);
