-- Words mined from text.
--
-- The sentence is stored with the word deliberately. A word without the context
-- you met it in is much harder to remember, and capturing that context by hand is
-- exactly the friction that stops people making cards at all.
--
-- Vocabulary is not scheduled here — it goes to Anki. Only kanji handwriting has
-- a review table, because Anki cannot check handwriting.

create table vocab_item (
    id            bigint      generated by default as identity primary key,
    user_id       bigint      not null references app_user (id) on delete cascade,
    -- The dictionary form, which is what the tokenizer matches on and therefore
    -- what "do I already know this?" has to compare against.
    term          text        not null,
    reading       text,
    meaning       text        not null,
    dict_entry_id text,
    sentence      text,
    source        text,
    created_at    timestamptz not null default now(),
    -- One row per word per user: saving a word twice should update, not duplicate.
    unique (user_id, term)
);

create index idx_vocab_user_created on vocab_item (user_id, created_at desc);
